stu_wait.php done
ccu-dorm-for-grads/ccu-dorm-for-grads pull request #65
Opened 2023-12-15 16:51 UTC by jasonbombbro

先分辨是否是遞補申請的時間，是的話，確認學生可否申請遞補申請

2023-12-16 01:32 UTC, WaltsonZh requested changes
1. $year in index.php
2. .stu_wait void class ?

2023-12-18 05:27 UTC, jasonbombbro commented
修好了應該

2023-12-18 13:04 UTC, WaltsonZh requested changes

2023-12-18 13:04 UTC, WaltsonZh commented on stu/stu_wait.php
> +    if($year<strtotime($valid_date["stusl_open"])||$year>strtotime($valid_date["stusl_close"])){
strtotime 回傳的是 epoch time
year = 111

2023-12-18 13:04 UTC, WaltsonZh commented on stu/stu_wait.php
>          if($info===0){
false === 0 ?

2023-12-18 16:01 UTC, jasonbombbro commented on stu/stu_wait.php
> +    if($year<strtotime($valid_date["stusl_open"])||$year>strtotime($valid_date["stusl_close"])){
這邊是我的疏失，但判斷有沒有超過時限這部分應該得砍掉了，因為如果只判斷民國年($year)而已不夠足以判斷有無在time_limit的stusl_open和stusl_close的時間內，因為還需要判斷月日時分秒

2023-12-19 02:08 UTC, WaltsonZh requested changes

2023-12-19 02:08 UTC, WaltsonZh commented on stu/stu_wait.php
> +    if(count($info)==0){
`count(false) == 0` ?????????

2023-12-19 11:56 UTC, jasonbombbro commented on stu/stu_wait.php
> +    if(count($info)==0){
solve

2023-12-20 00:48 UTC, WaltsonZh approved these changes
LGTM!!!!!

2023-12-20 00:48 UTC, merged