Bunches of Changes / Improvements
ccu-dorm-for-grads/ccu-dorm-for-grads pull request #72
Opened 2023-12-18 20:41 UTC by dachangjames

1. Added a new file token_generator.js to generate a token for the user automatically.
2. Finalized the admapply.php file for the admin to perform the application process.
3. Finalized the admapply_unit.php file for the admin to add a new unit or edit an existing unit.
4. Modified the DB.php file: added a new function called advanced_fetch_row
   to fetch a row from the database with two conditions being checked instead of one.
5. Modified the Dotenv.php file: minor change in line 13.
   The backslash \ was removed because it's unnecessary and may cause errors when using a different OS.
6. Modified the qryindex.php file: Improved the layout because, from my perspective, my old design looks like trash.
7. Modified the stuindex.php file: Improved the layout because, from my perspective, my old design also looks like trash.

2023-12-19 02:05 UTC, WaltsonZh requested changes

2023-12-19 03:12 UTC, dachangjames commented on token_generator.js
Oops sorry, I forgot to mention that this tool is for developers only. When handing the deliverable to the customer, this file can and shall be deleted.

2023-12-19 03:30 UTC, dachangjames commented on adm/admapply.php
> +    else
That will cause warning messages and an empty table to show up when entering this page, and the utility of filtering departments will crash as well. That's why it's necessary to deliberately make the page die for once.
Btw, did you run my code and examine the result before requesting these changes?

2023-12-19 03:31 UTC, dachangjames commented on adm/admapply.php
> +  }
Explanation as the second comment.

2023-12-19 03:37 UTC, dachangjames commented on adm/admapply.php
> +    else
Looking forward to your reply.

2023-12-19 05:41 UTC, WaltsonZh commented on token_generator.js
If it is for developers then this file is unnessesary.
Developers can use node.js console or browser console to generate those keys.

2023-12-19 05:43 UTC, WaltsonZh commented on adm/admapply.php
> +    else
I apologize for the mistake in the snippet above.
```
if (isset($_POST["unit_name"])) {
  $unit_parent = $_POST["unit_name"];
}
```
This should work now!

2023-12-19 08:19 UTC, dachangjames commented on adm/admapply.php
> +    else
Unfortunately, the problem persists after the modification. Perhaps it's because I typed something wrong in my syntax; maybe we can have a mini-online meeting tomorrow to address the issue faster? (My schedule is full tonight, apologies for the inconvenience.)

2023-12-19 08:24 UTC, dachangjames commented on adm/admapply.php
> +    else
Also, here's the modified code, I dunno if I had typed sth wrong:
![螢幕擷取畫面 2023-12-19 162045](https://github.com/ccu-dorm-for-grads/ccu-dorm-for-grads/assets/91360472/44ddc833-9a91-4385-a920-6eaa318016d7)
![螢幕擷取畫面 2023-12-19 162149](https://github.com/ccu-dorm-for-grads/ccu-dorm-for-grads/assets/91360472/ca486d8b-b989-4e38-bb64-d426541df82b)

2023-12-19 08:25 UTC, dachangjames commented on token_generator.js
I see, I will delete this file in the next push commit.

2023-12-19 08:31 UTC, dachangjames commented on adm/admapply.php
> +    else
https://github.com/ccu-dorm-for-grads/ccu-dorm-for-grads/assets/91360472/5d3a52a7-2439-48a8-b842-7ae5fd262514

2023-12-19 08:34 UTC, dachangjames commented on adm/admapply.php
> +    else
Perhaps I had done something stupid according to the error messages shown in the video, but I'm not certain...

2023-12-20 05:37 UTC, WaltsonZh approved these changes
LGTM!!!!!

2023-12-20 05:37 UTC, merged